[package]
name = "rust-markov-lib"
version = "0.1.0"
authors = ["Jennifer Renoux <jennifer.renoux@oru.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float-cmp = "*"
vose-alias = "1.0.0"